# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-08 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd', '0003_auto_20180708_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='publicid',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
