# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmd', '0004_auto_20180708_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
